//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationConfig
    {
        public ApplicationConfig()
        {
            this.ApplicationMasters = new HashSet<ApplicationMaster>();
            this.ApprovalHistories = new HashSet<ApprovalHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Code { get; set; }
        public bool Active { get; set; }
        public Nullable<int> DeptId { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> ApprovalKind { get; set; }
        public string ApprovalLineDefault { get; set; }
        public string ApprovalLineJson { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    
        public virtual HrDeptMaster HrDeptMaster { get; set; }
        public virtual HrEmpMaster HrEmpMaster { get; set; }
        public virtual HrEmpMaster HrEmpMaster1 { get; set; }
        public virtual ICollection<ApplicationMaster> ApplicationMasters { get; set; }
        public virtual ICollection<ApprovalHistory> ApprovalHistories { get; set; }
    }
}
