//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationMaster
    {
        public ApplicationMaster()
        {
            this.InstallNetworks = new HashSet<InstallNetwork>();
            this.ItEquipments = new HashSet<ItEquipment>();
            this.PhoneServices = new HashSet<PhoneService>();
            this.SystemRoles = new HashSet<SystemRole>();
            this.ApprovalHistories = new HashSet<ApprovalHistory>();
            this.Approvals = new HashSet<Approval>();
            this.Approvals1 = new HashSet<Approval>();
            this.EmailAddresses = new HashSet<EmailAddress>();
            this.InformationSystems = new HashSet<InformationSystem>();
            this.CCTVPolicies = new HashSet<CCTVPolicy>();
            this.NetClientPolicies = new HashSet<NetClientPolicy>();
        }
    
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public string Subject { get; set; }
        public string Code { get; set; }
        public string Applicant { get; set; }
        public System.DateTime RequestDate { get; set; }
        public string CostCenter { get; set; }
        public int DeptId { get; set; }
        public string System { get; set; }
        public System.Guid ApprovalKind { get; set; }
        public string ApprovalLine { get; set; }
        public string ApprovalLineJson { get; set; }
        public System.Guid ApprovalStatus { get; set; }
        public string NextApprover { get; set; }
        public Nullable<System.DateTime> ConfirmDate { get; set; }
        public string Description { get; set; }
        public string Opinion { get; set; }
        public string ContactPerson { get; set; }
        public string Content { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUId { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUid { get; set; }
    
        public virtual HrDeptMaster HrDeptMaster { get; set; }
        public virtual ApplicationConfig ApplicationConfig { get; set; }
        public virtual ICollection<InstallNetwork> InstallNetworks { get; set; }
        public virtual ICollection<ItEquipment> ItEquipments { get; set; }
        public virtual ICollection<PhoneService> PhoneServices { get; set; }
        public virtual ICollection<SystemRole> SystemRoles { get; set; }
        public virtual ICollection<ApprovalHistory> ApprovalHistories { get; set; }
        public virtual ICollection<Approval> Approvals { get; set; }
        public virtual ICollection<Approval> Approvals1 { get; set; }
        public virtual ICollection<EmailAddress> EmailAddresses { get; set; }
        public virtual ICollection<InformationSystem> InformationSystems { get; set; }
        public virtual ICollection<CCTVPolicy> CCTVPolicies { get; set; }
        public virtual ICollection<NetClientPolicy> NetClientPolicies { get; set; }
    }
}
