//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Approval
    {
        public int Id { get; set; }
        public int ApplicationId { get; set; }
        public int MasterId { get; set; }
        public string EmpId { get; set; }
        public Nullable<System.Guid> ApproverType { get; set; }
        public Nullable<bool> IsView { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<System.DateTime> DateApprove { get; set; }
        public byte Seq { get; set; }
        public string Comment { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
        public virtual ApplicationMaster ApplicationMaster1 { get; set; }
    }
}
