//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApprovalHistory
    {
        public int Id { get; set; }
        public string ApprovalLine { get; set; }
        public string ApprovalLineJson { get; set; }
        public int ApplicationId { get; set; }
        public int MasterId { get; set; }
        public string CreateUid { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual ApplicationConfig ApplicationConfig { get; set; }
        public virtual ApplicationMaster ApplicationMaster { get; set; }
    }
}
