//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CmsPostAction
    {
        public int ActionId { get; set; }
        public System.Guid ModuleId { get; set; }
        public int MasterId { get; set; }
        public System.Guid CategoryId { get; set; }
        public string UserId { get; set; }
        public System.DateTime ActionDate { get; set; }
        public Nullable<bool> IsAttachFile { get; set; }
    
        public virtual SysCategoryValue SysCategoryValue { get; set; }
        public virtual HrEmpMaster HrEmpMaster { get; set; }
        public virtual SysCategoryValue SysCategoryValue1 { get; set; }
    }
}
