//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrDeptMasterFull
    {
        public int Id { get; set; }
        public string Code { get; set; }
        public string EnName { get; set; }
        public string KoName { get; set; }
        public Nullable<int> Organization { get; set; }
        public Nullable<int> Plant { get; set; }
        public Nullable<int> Dept { get; set; }
        public Nullable<int> Sect { get; set; }
        public string OrganizationName { get; set; }
        public string PlantName { get; set; }
        public string DeptName { get; set; }
        public string SectName { get; set; }
        public Nullable<int> Level { get; set; }
        public string CostCenter { get; set; }
    }
}
