//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrDeptMaster
    {
        public HrDeptMaster()
        {
            this.HrDeptMaster1 = new HashSet<HrDeptMaster>();
            this.HrEmpMasters = new HashSet<HrEmpMaster>();
            this.ApplicationConfigs = new HashSet<ApplicationConfig>();
            this.ApplicationMasters = new HashSet<ApplicationMaster>();
        }
    
        public int Id { get; set; }
        public string Code { get; set; }
        public string EnName { get; set; }
        public string KoName { get; set; }
        public bool IsDelete { get; set; }
        public Nullable<int> Parent { get; set; }
        public string ParentCode { get; set; }
    
        public virtual ICollection<HrDeptMaster> HrDeptMaster1 { get; set; }
        public virtual HrDeptMaster HrDeptMaster2 { get; set; }
        public virtual ICollection<HrEmpMaster> HrEmpMasters { get; set; }
        public virtual ICollection<ApplicationConfig> ApplicationConfigs { get; set; }
        public virtual ICollection<ApplicationMaster> ApplicationMasters { get; set; }
    }
}
