//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HrEmpMaster
    {
        public HrEmpMaster()
        {
            this.CmsFormTemplates = new HashSet<CmsFormTemplate>();
            this.CmsFormTemplates1 = new HashSet<CmsFormTemplate>();
            this.CmsFormTemplates2 = new HashSet<CmsFormTemplate>();
            this.CmsFormTemplates3 = new HashSet<CmsFormTemplate>();
            this.CmsPostActions = new HashSet<CmsPostAction>();
            this.CmsPosts = new HashSet<CmsPost>();
            this.CmsPosts1 = new HashSet<CmsPost>();
            this.CmsPosts2 = new HashSet<CmsPost>();
            this.SysCategories = new HashSet<SysCategory>();
            this.SysCategoryValues = new HashSet<SysCategoryValue>();
            this.SysCategoryValues1 = new HashSet<SysCategoryValue>();
            this.SysCategories1 = new HashSet<SysCategory>();
            this.SysCategories2 = new HashSet<SysCategory>();
            this.SysUserMappings = new HashSet<SysUserMapping>();
            this.SysCategoryValues2 = new HashSet<SysCategoryValue>();
            this.ApplicationConfigs = new HashSet<ApplicationConfig>();
            this.ApplicationConfigs1 = new HashSet<ApplicationConfig>();
        }
    
        public string EmpId { get; set; }
        public string Code { get; set; }
        public string LocalName { get; set; }
        public string KoName { get; set; }
        public string EnName { get; set; }
        public string Email { get; set; }
        public string Sex { get; set; }
        public string Nation { get; set; }
        public string PositionId { get; set; }
        public bool Status { get; set; }
        public int DeptCode { get; set; }
        public byte[] Img { get; set; }
        public string WorkGroup { get; set; }
        public string Temp { get; set; }
        public Nullable<int> FactoryId { get; set; }
        public string Password { get; set; }
        public System.Guid uStatus { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<System.DateTime> InterfaceDate { get; set; }
        public Nullable<System.DateTime> ActiveDate { get; set; }
        public string Costcenter { get; set; }
    
        public virtual ICollection<CmsFormTemplate> CmsFormTemplates { get; set; }
        public virtual ICollection<CmsFormTemplate> CmsFormTemplates1 { get; set; }
        public virtual ICollection<CmsFormTemplate> CmsFormTemplates2 { get; set; }
        public virtual ICollection<CmsFormTemplate> CmsFormTemplates3 { get; set; }
        public virtual ICollection<CmsPostAction> CmsPostActions { get; set; }
        public virtual ICollection<CmsPost> CmsPosts { get; set; }
        public virtual ICollection<CmsPost> CmsPosts1 { get; set; }
        public virtual ICollection<CmsPost> CmsPosts2 { get; set; }
        public virtual HrDeptMaster HrDeptMaster { get; set; }
        public virtual ICollection<SysCategory> SysCategories { get; set; }
        public virtual ICollection<SysCategoryValue> SysCategoryValues { get; set; }
        public virtual ICollection<SysCategoryValue> SysCategoryValues1 { get; set; }
        public virtual ICollection<SysCategory> SysCategories1 { get; set; }
        public virtual ICollection<SysCategory> SysCategories2 { get; set; }
        public virtual ICollection<SysUserMapping> SysUserMappings { get; set; }
        public virtual ICollection<SysCategoryValue> SysCategoryValues2 { get; set; }
        public virtual ICollection<ApplicationConfig> ApplicationConfigs { get; set; }
        public virtual ICollection<ApplicationConfig> ApplicationConfigs1 { get; set; }
    }
}
