//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformationSystem
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public System.Guid System { get; set; }
        public System.Guid Seriousness { get; set; }
        public string Explanation { get; set; }
        public string EmpId { get; set; }
        public Nullable<int> NumDays { get; set; }
        public string Solution { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
    }
}
