//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InstallNetwork
    {
        public int Id { get; set; }
        public int MasterId { get; set; }
        public string ItemName { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Desciption { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public Nullable<System.DateTime> RequestToVendorDate { get; set; }
        public Nullable<System.DateTime> ReceivedQuotationDate { get; set; }
        public Nullable<System.DateTime> RequestToDeptDate { get; set; }
        public Nullable<System.DateTime> ApprDate { get; set; }
        public string ApprEmpId { get; set; }
        public Nullable<System.DateTime> PartnerSurveyDate { get; set; }
        public Nullable<System.DateTime> PartnerSendQuotationDate { get; set; }
        public Nullable<System.DateTime> StartedDate { get; set; }
        public Nullable<System.DateTime> FinishedDate { get; set; }
        public Nullable<double> Amount { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
    
        public virtual ApplicationMaster ApplicationMaster { get; set; }
    }
}
