//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubSystem
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public bool Status { get; set; }
        public string CreateUid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUid { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
