//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysAuthorization
    {
        public int Id { get; set; }
        public string Action { get; set; }
        public string Controller { get; set; }
        public bool IsAllowed { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUid { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUid { get; set; }
        public string Owner { get; set; }
    }
}
