//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysCategoryValue
    {
        public SysCategoryValue()
        {
            this.Attachments = new HashSet<Attachment>();
            this.CmsPostActions = new HashSet<CmsPostAction>();
            this.CmsPostActions1 = new HashSet<CmsPostAction>();
            this.SysCategoryValue1 = new HashSet<SysCategoryValue>();
        }
    
        public System.Guid ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.Guid> Dictionary { get; set; }
        public Nullable<byte> Sequence { get; set; }
        public bool Actived { get; set; }
        public System.Guid Category { get; set; }
        public Nullable<System.Guid> ParentID { get; set; }
        public string Remark { get; set; }
        public string CreateUid { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string UpdateUid { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string DeleteUid { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string SubCode { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<CmsPostAction> CmsPostActions { get; set; }
        public virtual ICollection<CmsPostAction> CmsPostActions1 { get; set; }
        public virtual HrEmpMaster HrEmpMaster { get; set; }
        public virtual HrEmpMaster HrEmpMaster1 { get; set; }
        public virtual HrEmpMaster HrEmpMaster2 { get; set; }
        public virtual SysCategory SysCategory { get; set; }
        public virtual ICollection<SysCategoryValue> SysCategoryValue1 { get; set; }
        public virtual SysCategoryValue SysCategoryValue2 { get; set; }
    }
}
