//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SingleSignOn.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SysRole
    {
        public SysRole()
        {
            this.SysRoleMappings = new HashSet<SysRoleMapping>();
            this.SysUserMappings = new HashSet<SysUserMapping>();
        }
    
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public System.Guid SystemId { get; set; }
        public string Description { get; set; }
        public bool Status { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> DeleteDate { get; set; }
        public string DeleteUser { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual ICollection<SysRoleMapping> SysRoleMappings { get; set; }
        public virtual ICollection<SysUserMapping> SysUserMappings { get; set; }
    }
}
